version: '3.8'

services:
  # Development fortress-panel with hot reload
  fortress-panel-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: fortress-panel-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "3000:3000"
      - "9229:9229"  # Node.js debug port
    environment:
      NODE_ENV: development
      DEBUG=fortress-panel:*
      DB_HOST: mariadb-dev
      DB_PORT: 3306
      DB_NAME: fortress_panel_dev
      DB_USERNAME: fortress_user
      DB_PASSWORD: dev_password_123
      REDIS_HOST: redis-dev
      REDIS_PORT: 6379
      JWT_SECRET: dev-jwt-secret-key-for-development-only
      ENCRYPTION_KEY: dev-encryption-key-1234567890123456
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: test
      SMTP_PASS: test
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - fortress_dev_uploads:/var/lib/fortress-panel/uploads
      - fortress_dev_apps:/var/lib/fortress-panel/apps
      - fortress_dev_logs:/var/log/fortress-panel
    depends_on:
      mariadb-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    networks:
      - fortress-dev-network
    command: npm run dev

  # Development MariaDB
  mariadb-dev:
    image: mariadb:10.11
    container_name: fortress-mariadb-dev
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password_123
      MYSQL_DATABASE: fortress_panel_dev
      MYSQL_USER: fortress_user
      MYSQL_PASSWORD: dev_password_123
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mariadb_dev_data:/var/lib/mysql
      - ./docker/config/mysql/my-dev.cnf:/etc/mysql/my.cnf
    networks:
      - fortress-dev-network
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/log/mysql/general.log

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    container_name: fortress-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    networks:
      - fortress-dev-network

  # Mail testing service
  mailhog:
    image: mailhog/mailhog:latest
    container_name: fortress-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - fortress-dev-network

  # Development phpMyAdmin
  phpmyadmin-dev:
    image: phpmyadmin:latest
    container_name: fortress-phpmyadmin-dev
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb-dev
      PMA_PORT: 3306
      PMA_USER: fortress_user
      PMA_PASSWORD: dev_password_123
      MYSQL_ROOT_PASSWORD: dev_root_password_123
    depends_on:
      - mariadb-dev
    networks:
      - fortress-dev-network

  # Development Node.js runtime with hot reload
  nodejs-dev-runtime:
    image: node:20-alpine
    container_name: fortress-nodejs-dev
    restart: unless-stopped
    ports:
      - "3002:3000"
      - "9230:9229"  # Debug port
    working_dir: /app
    volumes:
      - fortress_dev_apps:/app
      - ./docker/scripts/nodejs-dev-entrypoint.sh:/entrypoint.sh
    command: sh /entrypoint.sh
    networks:
      - fortress-dev-network
    profiles:
      - dev-runtimes

  # Development Python runtime with hot reload
  python-dev-runtime:
    image: python:3.11-slim
    container_name: fortress-python-dev
    restart: unless-stopped
    ports:
      - "8001:8000"
    working_dir: /app
    volumes:
      - fortress_dev_apps:/app
      - ./docker/scripts/python-dev-entrypoint.sh:/entrypoint.sh
    command: sh /entrypoint.sh
    networks:
      - fortress-dev-network
    profiles:
      - dev-runtimes

  # Development PHP runtime with hot reload
  php-dev-runtime:
    image: php:8.2-apache
    container_name: fortress-php-dev
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - fortress_dev_apps:/var/www/html
      - ./docker/config/php/php-dev.ini:/usr/local/etc/php/php.ini
    networks:
      - fortress-dev-network
    profiles:
      - dev-runtimes

  # Development tools
  adminer:
    image: adminer:latest
    container_name: fortress-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - mariadb-dev
    networks:
      - fortress-dev-network
    profiles:
      - dev-tools

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: fortress-redis-commander
    restart: unless-stopped
    ports:
      - "8083:8081"
    environment:
      REDIS_HOSTS: local:redis-dev:6379
    depends_on:
      - redis-dev
    networks:
      - fortress-dev-network
    profiles:
      - dev-tools

  # Database documentation tool
  schemacrawler:
    image: schemacrawler/schemacrawler:latest
    container_name: fortress-schemacrawler
    restart: "no"
    volumes:
      - ./docker/scripts/schemacrawler.sh:/scripts/schemacrawler.sh
    command: sh /scripts/schemacrawler.sh
    depends_on:
      - mariadb-dev
    networks:
      - fortress-dev-network
    profiles:
      - dev-tools

volumes:
  # Development volumes
  mariadb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  fortress_dev_uploads:
    driver: local
  fortress_dev_apps:
    driver: local
  fortress_dev_logs:
    driver: local

networks:
  fortress-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16